FROM eclipse-temurin:25-jre-alpine
ARG SERVICE_NAME
WORKDIR /app
COPY services/${SERVICE_NAME}/target/${SERVICE_NAME}-0.1.0-SNAPSHOT.jar app.jar
ENV SERVER_PORT=8080
EXPOSE 8080
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75", "-jar", "/app/app.jar"]
